project:
  type: book
  output-dir: docs

book:
  title: "Statistical Methods for Transport Planning - Workbook"
  author: "Rafael Verduzco-Torres"
  chapters:
    - index.qmd
    - session-1.qmd
    - session-2.qmd
    - session-3.qmd
    - session-4.qmd
    - session-5.qmd
    - session-6.qmd
    - session-7.qmd
execute:
  message: false
  warning: false

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    cover-image: images/cover.png
    toc: true



